# Stage 1: Build (jdk needed)
FROM eclipse-temurin:21-jdk AS build

RUN apt-get update && \
    apt-get install -y maven && \
	apt-get install -y dos2unix
	
WORKDIR /common
COPY ah5-common-java-spring .
RUN mvn clean install -DskipTests

WORKDIR /app
COPY ah5-core-java-spring .
RUN dos2unix /app/serviceorchestration-dynamic/docker/entrypoint.sh
RUN mvn -pl serviceorchestration-dynamic -am -DskipTests clean install

# Stage 2: Runtime (jdk not needed)
FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /app/serviceorchestration-dynamic/target/arrowhead-serviceorchestration-dynamic-5.0.0.jar arrowhead-serviceorchestration-dynamic-5.0.0.jar
COPY --from=build /app/serviceorchestration-dynamic/target/application.properties config_temp/application.properties
COPY --from=build /app/serviceorchestration-dynamic/target/log4j2.xml config_temp/log4j2.xml
COPY --from=build /app/serviceorchestration-dynamic/src/main/resources/certificate config_temp/certificte
COPY --from=build /app/serviceorchestration-dynamic/docker/entrypoint.sh entrypoint.sh

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]