# Stage 1: Build (jdk needed)
FROM eclipse-temurin:21-jdk AS build

ARG AH_VERSION

RUN apt-get update && \
    apt-get install -y maven && \
	apt-get install -y dos2unix
	
WORKDIR /common
COPY ah5-common-java-spring .
RUN mvn clean install -DskipTests

WORKDIR /app
COPY ah5-core-java-spring .
RUN dos2unix /app/serviceorchestration-simple/docker/entrypoint.sh
RUN mvn -pl serviceorchestration-simple -am -DskipTests clean install

# Stage 2: Runtime (jdk not needed)
FROM eclipse-temurin:21-jre

ARG AH_VERSION
ENV AH_VERSION=$AH_VERSION

WORKDIR /app
COPY --from=build /app/serviceorchestration-simple/target/arrowhead-serviceorchestration-simple-${AH_VERSION}.jar arrowhead-serviceorchestration-simple-${AH_VERSION}.jar
COPY --from=build /app/serviceorchestration-simple/target/application.properties config_temp/application.properties
COPY --from=build /app/serviceorchestration-simple/target/log4j2.xml config_temp/log4j2.xml
COPY --from=build /app/serviceorchestration-simple/src/main/resources/certificate config_temp/certificte
COPY --from=build /app/serviceorchestration-simple/docker/entrypoint.sh entrypoint.sh

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]