-- Logs

CREATE TABLE IF NOT EXISTS logs (
  log_id VARCHAR(100) NOT NULL,
  entry_date TIMESTAMP(3) NULL DEFAULT NULL,
  logger VARCHAR(100) DEFAULT NULL,
  log_level VARCHAR(100) DEFAULT NULL,
  message CLOB,
  exception CLOB,
  PRIMARY KEY (log_id)
);

-- Subscription

CREATE TABLE IF NOT EXISTS subscription (
  id UUID NOT NULL,
  owner_system VARCHAR(63) NOT NULL,
  target_system VARCHAR(63) NOT NULL,
  service_definition VARCHAR(63) NOT NULL,
  expires_at TIMESTAMP,
  notify_protocol VARCHAR(14) NOT NULL,
  notify_properties CLOB NOT NULL,
  orchestration_request CLOB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (owner_system, target_system, service_definition)
);

-- Orchestration Job

CREATE TABLE IF NOT EXISTS orchestration_job (
  id UUID NOT NULL,
  status VARCHAR(14) NOT NULL,
  type VARCHAR(14) NOT NULL,
  requester_system VARCHAR(63) NOT NULL,
  target_system VARCHAR(63) NOT NULL,
  service_definition VARCHAR(63) NOT NULL,
  subscription_id VARCHAR(63),
  message CLOB,
  created_at TIMESTAMP NOT NULL,
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  PRIMARY KEY (id)
);

-- Orchestration Lock

CREATE TABLE IF NOT EXISTS orchestration_lock (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  orchestration_job_id VARCHAR(63),
  service_instance_id VARCHAR(255) NOT NULL,
  owner VARCHAR(63) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  temporary BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
);
